export const LOGIN='LOGIN';
export const SIGNUP='SIGNUP';
export const LOGOUT='LOGOUT';
export const SAVEID='SAVEID';
export const CHANGEPASSWORD='CHANGEPASSWORD';
export const G_PRODUCT_CATEGORY='G_PRODUCT_CATEGORY';
export const G_PRODUCT_DETAIL='G_PRODUCT_DETAIL';

export const GET_TO_CART = 'GET_TO_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';

export const CHECKOUT_TO_CART='CHECKOUT_TO_CART';
export const ORDERDETAIL_TO_CART='ORDERDETAIL_TO_CART';
export const BILLING_TO_CART='BILLING_TO_CART';
export const CONFIRM_TO_CART='CONFIRM_TO_CART';


